*** empty log message ***

diff --git a/campsite/configure b/campsite/configure
--- a/campsite/configure
+++ b/campsite/configure
@@ -4,12 +4,14 @@ export ROOT_USER=root
 export ROOT_GROUP=root
 define_start_env=no
 upgrade=""
+read_only=false
 while [ "$1" != "" ]; do
     case $1 in
     --define_start_env) define_start_env=yes ;;
     --upgrade) upgrade=--upgrade ;;
     --root_user) export ROOT_USER=$2; shift 1 ;;
     --root_group) export ROOT_GROUP=$2; shift 1 ;;
+    --read_only) read_only=true ;;
     esac
     shift 1
 done
@@ -36,12 +38,23 @@ if [ "$define_start_env" != "yes" ]; then
 
 rm -f make.env
 
-do_install_full_config $upgrade
-[ $? -ne 0 ] && exit 1
-for sel_mod in $SELECTED_MODULES; do
-    do_module_full_config $sel_mod $upgrade
+if [ "$read_only" = "false" ]; then
+    do_install_full_config $upgrade
     [ $? -ne 0 ] && exit 1
-done
+    for sel_mod in $SELECTED_MODULES; do
+	do_module_full_config $sel_mod $upgrade
+	[ $? -ne 0 ] && exit 1
+    done
+else
+    check4_make
+    prepare_install_env
+    install_conf --set
+    for sel_mod in $SELECTED_MODULES; do
+	prepare_${sel_mod}_env
+	modules_conf --set $sel_mod
+	[ $? -ne 0 ] && exit 1
+    done
+fi
 
 echo -n "Writing make.env file..."
 make_env=${CAMPSITE_PACKAGE_DIR}/make.env
@@ -87,7 +100,7 @@ for sel_mod in $SELECTED_MODULES; do
 	    fi
 	done
     fi
-    if ! in_list $sel_mod $written_list; then
+    if ! in_list $sel_mod $written_modules; then
 	attr_list=`modules_conf "$sel_mod" | cut -f 1 -d "#"`
 	for a in $attr_list; do
 	    echo "export $a" >> $make_env
@@ -96,34 +109,16 @@ for sel_mod in $SELECTED_MODULES; do
     fi
 done
 echo "done"
-for dir in implementation supplemental; do
-    if [ -x ${dir}/configure ]; then
-	echo "Configuring $dir ..."
-	cd $dir && ./configure
-	result=$?
-	cd ..
-	[ $result -ne 0 ] && echo "ERROR configuring $dir" && exit 1
-    fi
-done
+if [ "$read_only" = "false" ]; then
+    for dir in implementation supplemental; do
+	if [ -x ${dir}/configure ]; then
+	    echo "Configuring $dir ..."
+	    cd $dir && ./configure
+	    result=$?
+	    cd ..
+	    [ $result -ne 0 ] && echo "ERROR configuring $dir" && exit 1
+	fi
+    done
+fi
 echo "Configuration done"
-exit 0
-
-echo SELECTED_MODULES $SELECTED_MODULES
-echo IMPLEMENTATION_PARTS $IMPLEMENTATION_PARTS
-echo SUPPLEMENTAL_PARTS $SUPPLEMENTAL_PARTS
-echo CAMPSITE_VERSION $CAMPSITE_VERSION
-echo INSTALL_CONF $INSTALL_CONF
-echo CAMPSITE_PACKAGE_DIR $CAMPSITE_PACKAGE_DIR
-echo MYSQL_CONNECT $MYSQL_CONNECT
-echo SMTP_WRAPPER $SMTP_WRAPPER
-echo CAMPSITE_REGISTER $CAMPSITE_REGISTER
-echo INSTALL_LOG $INSTALL_LOG
-echo CHECKED_DEPENDENCIES $CHECKED_DEPENDENCIES
-echo CHECKED_MODULES $CHECKED_MODULES
-echo CONFIGURED_MODULES $CONFIGURED_MODULES
-echo INSTALL_CONFIGURED $INSTALL_CONFIGURED
-echo PACKAGE_TYPE $PACKAGE_TYPE
-echo PREPARED_MOD_ENV $PREPARED_MOD_ENV
-#install_conf
-#modules_conf $SELECTED_MODULES
 fi
diff --git a/campsite/implementation/parser/parser/configure b/campsite/implementation/parser/parser/configure
--- a/campsite/implementation/parser/parser/configure
+++ b/campsite/implementation/parser/parser/configure
@@ -51,7 +51,7 @@ test -x \$CAMPSITECTL || exit 0
 #
 #	See how we were called.
 #
-case "$1" in
+case "\$1" in
   start)
 	# Check if atd is already running
 	THREADS=\`ps ax | grep ${APP_NAME}_server| grep -v grep | wc -l\`
@@ -66,7 +66,7 @@ case "$1" in
   stop)
 	echo -n 'Stopping $APP_NAME daemon: '
 	\$CAMPSITECTL stop
-	if [ $? -ne 0 ]; then echo "ERROR"; else echo "OK"; fi
+	if [ \$? -ne 0 ]; then echo "ERROR"; else echo "OK"; fi
 	;;
   reload|restart)
 	\$0 stop
@@ -120,40 +120,40 @@ test -x \$CAMPSITE_SERVER || exit 0
 #
 #	See how we were called.
 #
-case "$1" in
+case "\$1" in
   start)
 	srv_proc=\`ps ax|grep -w ${APP_NAME}_server|grep -v grep|wc -l\`
 	if [ \$srv_proc -ne 0 ]; then
 	    exit 0
 	fi
 	\$CAMPSITE_SERVER
-	err_code=$?
-	if [ $err_code -ne 0 ]; then
+	err_code=\$?
+	if [ \$err_code -ne 0 ]; then
 	    exit 1
 	fi
 	srv_proc=\`ps ax|grep -w ${APP_NAME}_server|grep -v grep|wc -l\`
-	if [ $srv_proc -eq 0 ]; then
+	if [ \$srv_proc -eq 0 ]; then
 	    exit 1
 	fi
 	;;
   stop)
 	output=\`killall ${APP_NAME}_server\`
-	[ $? -ne 0 ] && echo $output && exit 1
+	[ \$? -ne 0 ] && echo \$output && exit 1
 	;;
   reload|restart)
-	$0 stop
-	$0 start
+	\$0 stop
+	\$0 start
 	;;
   status)
 	THREADS=\`ps ax | grep -w ${APP_NAME}_server| grep -v grep | wc -l\`
-	if [ $THREADS -gt 0 ]; then
+	if [ \$THREADS -gt 0 ]; then
 	    echo "${APP_NAME} server is running"
 	else
 	    echo "${APP_NAME} server is not running"
 	fi
 	;;
   *)
-	echo "Usage: $0 {start|stop|restart|reload|status}"
+	echo "Usage: \$0 {start|stop|restart|reload|status}"
 	exit 1
 esac
 exit 0
diff --git a/campsite/uninstall b/campsite/uninstall
--- a/campsite/uninstall
+++ b/campsite/uninstall
@@ -1,54 +1,20 @@
 #!/bin/sh
 
-check_if_installed()
+configure_campsite()
 {
-    continue="N"
-    old_path=$PATH
-    program=$1
-    shift
-    while [ "$1" != "" ]; do
-        if [ "$1" == "--continue" ]; then
-	    continue="Y"
-	elif [ "$1" == "--path" ]; then
-	    shift
-	    if [ "$1" != "" ]; then
-		PATH=$PATH:$1
-	    fi
-        fi
-	shift
-    done
-    echo -n -e "\t$program ... "
-    which $program > /dev/null 2>&1
+    rm -f install_log
+    echo -e "\nSTEP 1"
+    echo -n "Configuring campsite for uninstall..."
+    echo -e "###############################################\n\tConfiguring campsite\n" >> install_log
+    ./configure --read_only $* >> install_log 2>&1
     err_code=$?
-    PATH=$old_path
     if [ $err_code -ne 0 ]; then
-        echo "NOT FOUND"
-	if [ "$continue" != "Y" ]; then
-	    echo "Could not find $program. Please install it or set proper path."
-	    echo "Read INSTALL file for more information."
-    	    exit 1
-	else
-	    echo "Could not find $program. It may not be installed or is not in your path."
-	    echo "You can go on installing but the application won't work without it."
-	    echo -n "Do you want to go on installing (Y/N) ? [Y]: "
-	    read yn
-	    if [ "$yn" == "" ]; then
-		yn="Y"
-	    fi
-	    if [ "${yn:0:1}" != "Y" ] && [ "${yn:0:1}" != "y" ]; then
-		echo "Aborting..."
-		exit 1
-	    fi
-	fi
-    else
-        echo "OK"
+	echo "ERROR."
+	echo "Read install_log for more information on configuration error."
+	echo "Please report bug to http://www.campware.org/bugs"
+	exit 1
     fi
-}
-
-check_components()
-{
-    echo -e "\nSTEP 1\nChecking for installed components:"
-    check_if_installed make --path "/bin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"
+    echo "done"
 }
 
 backup_database()
@@ -96,10 +62,10 @@ uninstall_campsite()
     make uninstall >> uninstall_log 2>&1
     err_code=$?
     if [ $err_code -ne 0 ]; then
-        echo "ERROR."
-        echo "Read uninstall_log for more information on uninstall error."
-        echo "Please report bug to http://www.campware.org/campsite/bugs.htm"
-        exit 1
+	echo "ERROR."
+	echo "Read uninstall_log for more information on uninstall error."
+	echo "Please report bug to http://www.campware.org/campsite/bugs.htm"
+	exit 1
     fi
     echo -e "\nCAMPSITE was uninstalled successfully."
     echo "For a complete uninstallation log read uninstall_log file."
@@ -114,10 +80,7 @@ if [ "$1" == "go_to_uninstall" ] && [ $my_id -eq 0 ]; then
     uninstall_campsite
     exit 0
 fi
-version=`cat ./README | grep -w ^version | grep ":" | cut -f 2 -d ":"`
-version=`echo $version`
-release_date=`cat ./README | grep -w ^release | grep ":" | cut -f 2 -d ":"`
-release_date=`echo $release_date`
+. ./configure --define_start_env $*
 if [ "$1" == "--version" ]; then
     echo -e "CAMPSITE $version, released on $release_date"
     exit 0
@@ -127,7 +90,7 @@ if [ $my_id -ne 0 ]; then
     echo -e "\nYou are not logged in as root. Without root access this application"
     echo "can not be installed. You will be prompted for root password."
 fi
-check_components
+configure_campsite $*
 backup_database
 rm -f uninstall_log
 if [ $my_id -ne 0 ]; then
@@ -135,9 +98,9 @@ if [ $my_id -ne 0 ]; then
     while true; do
 	echo -n "Root password: "
 	archive_path=`pwd`
-        su - --command="echo ""; export DROP_DB=$DROP_DB; cd $archive_path; ./uninstall go_to_uninstall" 2> /dev/null
-        err_code=$?
-        if [ $err_code -ne 0 ]; then
+	su - --command="echo ""; export DROP_DB=$DROP_DB; cd $archive_path; ./uninstall go_to_uninstall" #2> /dev/null
+	err_code=$?
+	if [ $err_code -ne 0 ]; then
 	    echo -n -e "\nThe password was not correct. Try again (Y/N) ? [Y]: "
 	    read yn
 	    if [ "$yn" == "" ]; then
@@ -149,7 +112,7 @@ if [ $my_id -ne 0 ]; then
 	    fi
 	else
 	    exit 0
-        fi
+	fi
     done
 else
     uninstall_campsite
