read parameters before su; filled in usage text

diff --git a/campsite/translation b/campsite/translation
--- a/campsite/translation
+++ b/campsite/translation
@@ -1,9 +1,70 @@
 #!/bin/sh
 
-USER_NAME=`id -un`
-GROUP_NAME=`id -gn`
+LANG=""
+FILE=""
+to_do="print_usage"
+pn=1
+while [ "${!pn}" != "" ]; do
+    case ${!pn} in
+    --make_package)
+	to_do=package
+	pn=`expr $pn + 1`
+	LANG=${!pn}
+	if [ "$LANG" = "" ]; then
+	    to_do=print_usage
+	fi
+	;;
+    --install_package)
+	to_do=install
+	pn=`expr $pn + 1`
+	FILE=${!pn}
+	if [ "$FILE" = "" ]; then
+	    to_do=print_usage
+	fi
+	;;
+    --user)
+	pn=`expr $pn + 1`
+	USER_NAME="${!pn}"
+	;;
+    --group)
+	pn=`expr $pn + 1`
+	GROUP_NAME="${!pn}"
+	;;
+    --add_trans_to_dist)
+	to_do=add_trans
+	pn=`expr $pn + 1`
+	LANG=${!pn}
+	if [ "$LANG" = "" ]; then
+	    to_do=print_usage
+	fi
+	;;
+#    --) ;;
+    esac
+    pn=`expr $pn + 1`
+done
+
+if [ "$to_do" = "print_usage" ]; then
+    echo -e "usage:\t./translation --make_package <language_code>"
+    echo -e "		Make translation package for specified language from"
+    echo -e "		application translation files in install directory."
+    echo -e "or\t./translation --install_package <package_file>"
+    echo -e "		Install translation files from a package to the application"
+    echo -e "		install directory."
+    echo -e "or\t./translation --add_trans_to_dist <language_code>"
+    echo -e "		Copy translation files for specified language from the"
+    echo -e "		application install directory to the distribution directory."
+    exit 2
+fi
+
+if [ ! -x ./configure ]; then
+    echo -e "Install script must be started from campsite directory!\nAborting..."
+    exit 2
+fi
+
 my_id=`id -u`
 if [ $my_id -ne 0 ]; then
+    USER_NAME=`id -un`
+    GROUP_NAME=`id -gn`
     echo -e "\nPlease supply root password."
     while true; do
 	echo -n "Root password: "
@@ -11,7 +72,7 @@ if [ $my_id -ne 0 ]; then
 	usr_grp="--user \"$USER_NAME\" --group \"$GROUP_NAME\""
 	su - --command="echo \"\"; cd $archive_path; ./translation $* $usr_grp" 2> /dev/null
 	err_code=$?
-	if [ $err_code -ne 0 ]; then
+	if [ $err_code -ne 0 ] && [ $err_code -ne 2 ]; then
 	    echo -n -e "\nThe password was not correct. Try again (Y/N) ? [Y]: "
 	    read yn
 	    if [ "$yn" = "" ]; then
@@ -19,7 +80,7 @@ if [ $my_id -ne 0 ]; then
 	    fi
 	    if [ "${yn:0:1}" != "Y" ] && [ "${yn:0:1}" != "y" ]; then
 		echo "Aborting..."
-		exit 1
+		exit 2
 	    fi
 	else
 	    exit 0
@@ -27,64 +88,10 @@ if [ $my_id -ne 0 ]; then
     done
 fi
 
-if [ ! -x ./configure ]; then
-    echo -e "Install script must be started from campsite directory!\nAborting..."
-    exit 1
-fi
-
-LANG=""
-FILE=""
-to_do="print_usage"
-while [ "$1" != "" ]; do
-    case $1 in
-    --make_package)
-	to_do=package
-	shift 1
-	LANG=$1
-	if [ "$LANG" = "" ]; then
-	    to_do=print_usage
-	fi
-	;;
-    --install_package)
-	to_do=install
-	shift 1
-	FILE=$1
-	if [ "$FILE" = "" ]; then
-	    to_do=print_usage
-	fi
-	;;
-    --user)
-	shift 1
-	USER_NAME="$1"
-	;;
-    --group)
-	shift 1
-	GROUP_NAME="$1"
-	;;
-    --add_trans_to_dist)
-	to_do=add_trans
-	shift 1
-	LANG=$1
-	if [ "$LANG" = "" ]; then
-	    to_do=print_usage
-	fi
-	;;
-#    --) ;;
-    esac
-    shift 1
-done
-
-if [ "$to_do" = "print_usage" ]; then
-    echo -e "usage:\t./translation --make_package <language_code>"
-    echo -e "or\t./translation --install_package <package_file>"
-    echo -e "or\t./translation --add_trans_to_dist <language_code>"
-    exit 1
-fi
-
 . ./configure --define_start_env
 if [ $? -ne 0 ]; then
     echo "Configure error. Make sure you configured campsite properly and try again."
-    exit 1
+    exit 2
 fi
 
 #clear
@@ -94,7 +101,7 @@ if [ $? -ne 0 ]; then
     echo "Error reading install files."
     echo "Please report bug to http://www.campware.org/bugs"
     echo "Aborting..."
-    exit 1
+    exit 2
 fi
 
 if [ "$to_do" = "package" ]; then
@@ -104,7 +111,7 @@ if [ "$to_do" = "package" ]; then
     if [ ! -f globals.$LANG.php ]; then
 	echo "no $LANG translation found"
 	popd &> /dev/null
-	exit 1
+	exit 2
     fi
 
     DST_DIR=/tmp/$$_$LANG
@@ -112,7 +119,7 @@ if [ "$to_do" = "package" ]; then
     if [ ! -d "$DST_DIR" ]; then
 	echo "error creating temporary directory"
 	popd &> /dev/null
-	exit 1
+	exit 2
     fi
 
     cp -f globals.$LANG.php $DST_DIR
@@ -139,7 +146,7 @@ fi
 if [ "$to_do" = "install" ]; then
     if [ ! -f "$FILE" ]; then
 	echo "invalid package file $FILE"
-	exit 1
+	exit 2
     fi
     cp -f "$FILE" "$PRIV_DIR"
 
@@ -148,6 +155,12 @@ if [ "$to_do" = "install" ]; then
     pushd "$PRIV_DIR" &> /dev/null
 
     tar xzf "$FILE"
+    if [ $? -ne 0 ]; then
+	popd &> /dev/null
+	popd &> /dev/null
+	echo "invalid package file"
+	exit 2
+    fi
     chown "$HTTP_USER"."$HTTP_GROUP" globals.*.php
     chmod 660 globals.*.php
     find . -name locals.\*.php -exec chown "$HTTP_USER"."$HTTP_GROUP" {} \;
@@ -170,14 +183,14 @@ if [ "$to_do" = "add_trans" ]; then
     if [ ! -f globals.$LANG.php ]; then
 	echo "no $LANG translation found"
 	popd &> /dev/null
-	exit 1
+	exit 2
     fi
 
     DST_DIR=`cut_last_dirs "$INSTALL_CONF"`/implementation/management
     if [ ! -d "$DST_DIR" ]; then
 	echo "distribution directory does not exist"
 	popd &> /dev/null
-	exit 1
+	exit 2
     fi
 
     cp -f globals.$LANG.php $DST_DIR
@@ -186,6 +199,7 @@ if [ "$to_do" = "add_trans" ]; then
     popd &> /dev/null
     pushd $DST_DIR &> /dev/null
 
+echo "user-group: $USER_NAME-$GROUP_NAME"
     chown "$USER_NAME"."$GROUP_NAME" globals.$LANG.php
     chmod 660 globals.$LANG.php
     find . -name locals.$LANG.php -exec chown "$USER_NAME"."$GROUP_NAME" {} \;
@@ -198,6 +212,3 @@ if [ "$to_do" = "add_trans" ]; then
 
     exit 0
 fi
-
-#if [ "$to_do" = "" ]; then
-#fi
