*** empty log message ***

diff --git a/campsite/.install_conf/install_functions b/campsite/.install_conf/install_functions
--- a/campsite/.install_conf/install_functions
+++ b/campsite/.install_conf/install_functions
@@ -150,7 +150,16 @@ if [ $? -ne 0 ]; then
     if [ "$choice" = "Y" ]; then
 	cc_upgrade=--upgrade
 	export upgrade=--upgrade
-	read_old_conf &> /dev/null
+	$INSTALL_CONF/read_app_conf
+	result=$?
+	if [ $result -ne 0 ]; then
+	    choice_yn "Error reading $APP_NAME configuration. Continue anyway?" Y
+	    if [ "$choice" = "N" ]; then
+		echo "Aborting..."
+		exit 1
+	    fi
+	fi
+	modules_conf --set
     fi
 fi
 while true; do
@@ -238,81 +247,4 @@ if [ "$choice" = "Y" ]; then
 fi
 choice_yn "Proceed with installation?" Y
 [ "$choice" = "N" ] && echo "Aborting..." && exit 1
-}
-
-read_old_conf()
-{
-mod_conf_file=$INSTALL_CONF/.modules.conf
-read_database_conf < $CONF_DIR/database.conf
-if [ $? -eq 0 ]; then
-    set_module_config DATABASE < $mod_conf_file
-fi
-if in_list PARSER $NEED_CONFIG_MODULES; then
-    read_parser_conf < $CONF_DIR/parser.conf
-    if [ $? -eq 0 ]; then
-	set_module_config PARSER < $mod_conf_file
-    fi
-fi
-if in_list ADMIN_INTERFACE $NEED_CONFIG_MODULES; then
-    modules_conf --set ADMIN_INTERFACE
-    read_tpl_cgi_conf < $CONF_DIR/tpl_cgi.conf
-    if [ $? -eq 0 ]; then
-	set_module_config ADMIN_INTERFACE < $mod_conf_file
-    fi
-fi
-if in_list EVENT_HANDLERS $NEED_CONFIG_MODULES; then
-    modules_conf --set EVENT_HANDLERS
-    read_smtp_conf < $CONF_DIR/smtp.conf
-    if [ $? -eq 0 ]; then
-	set_module_config EVENT_HANDLERS < $mod_conf_file
-    fi
-fi
-}
-
-read_database_conf()
-{
-while true; do
-    read dc_line
-    [ "$dc_line" = "" ] && return 0
-    dc_attr_name=`echo $dc_line | cut -f 1 -d " "`
-    let dc_start_char=${#dc_attr_name}+1
-    dc_attr_val=`echo $dc_line | cut -c ${dc_start_char}-`
-    export DATABASE_$dc_attr_name=`echo $dc_attr_val`
-done
-}
-
-read_parser_conf()
-{
-while true; do
-    read dc_line
-    [ "$dc_line" = "" ] && return 0
-    dc_attr_name=`echo $dc_line | cut -f 1 -d " "`
-    let dc_start_char=${#dc_attr_name}+1
-    dc_attr_val=`echo $dc_line | cut -c ${dc_start_char}-`
-    export PARSER_$dc_attr_name=`echo $dc_attr_val`
-done
-}
-
-read_tpl_cgi_conf()
-{
-while true; do
-    read dc_line
-    [ "$dc_line" = "" ] && return 0
-    dc_attr_name=`echo $dc_line | cut -f 1 -d " "`
-    let dc_start_char=${#dc_attr_name}+1
-    dc_attr_val=`echo $dc_line | cut -c ${dc_start_char}-`
-    export ADMIN_INTERFACE_$dc_attr_name=`echo $dc_attr_val`
-done
-}
-
-read_smtp_conf()
-{
-while true; do
-    read dc_line
-    [ "$dc_line" = "" ] && return 0
-    dc_attr_name=`echo $dc_line | cut -f 1 -d " "`
-    let dc_start_char=${#dc_attr_name}+1
-    dc_attr_val=`echo $dc_line | cut -c ${dc_start_char}-`
-    [ "$dc_attr_name" = "SERVER" ] && export EVENT_HANDLERS_SMTP_SERVER=`echo $dc_attr_val`
-done
 }
