- fix bug: exit when answer is no to upgrade - write .old_version file

diff --git a/campsite/.install_conf/install_functions b/campsite/.install_conf/install_functions
--- a/campsite/.install_conf/install_functions
+++ b/campsite/.install_conf/install_functions
@@ -160,7 +160,12 @@ if [ $? -ne 0 ]; then
 	    fi
 	fi
 	modules_conf --set
+    else
+	echo "Aborting..."
+	exit 1
     fi
+    export OLD_VERSION=`grep -w $APP_NAME /etc/campsite.reg | cut -f 2 -d ":"`
+    echo "$OLD_VERSION" > $INSTALL_CONF/../.old_version
 fi
 while true; do
     configure_install
