This commit was manufactured by cvs2svn to create tag 'CAMPSITE_2_2_3_RC2'.

diff --git a/campsite/.install_conf/install_functions b/campsite/.install_conf/install_functions
--- a/campsite/.install_conf/install_functions
+++ b/campsite/.install_conf/install_functions
@@ -4,11 +4,9 @@
 
 configure_campsite()
 {
-cc_upgrade=""
 cc_interactive=""
 while [ "$1" != "" ]; do
     case $1 in
-    --upgrade) cc_upgrade="$1" ;;
     --interactive) cc_interactive="$1" ;;
     esac
     shift 1
@@ -21,38 +19,35 @@ echo "campsite they must be configured."
 echo ""
 choice_yn "Do you want to read the description of campsite modules?" N
 if [ "$choice" = "Y" ]; then
-    clear
-    echo "Campsite modules description:"
+    echo -e "\nCampsite modules description:"
     modules_desc
-    echo -n -e "\nPress ENTER when ready"
+    echo -e "\nPress ENTER when ready"
     read
-    clear
 fi
 
 fi # interactive
 
 prepare_install_env || exit 1
 check_install_deps || exit 1
-check_install_config $cc_upgrade
-if $is_installed && [ "$cc_upgrade" != "--upgrade" ]; then
-    [ "$cc_interactive" != "--interactive" ] && exit 1
-    echo "There is another older campsite instance already installed."
-    choice_yn "Do you want to upgrade the current installation?" Y
-    if [ "$choice" = "Y" ]; then
-	cc_upgrade=--upgrade
-	export upgrade=--upgrade
-	modules_conf --set || return 1
-    else
-	echo "Installing new instance of campsite..."
-    fi
+check_install_config
+if $is_installed; then
+    echo -e "\nNOTE: Install found one or more older Campsite instance(s) already installed."
+    echo "If you want to upgrade older instances run:"
+    echo -e "\t$BIN_DIR/create_instance --db_name [instance_name]"
+    echo "script after finishing this install. Replace [instance_name] with"
+    echo "the Campsite instance name you want to upgrade. Run create_instance"
+    echo "script with --help option to get a list of available options."
+    echo -e "\nPress ENTER to continue"
+    read
 fi
 
 if [ "$cc_interactive" = "--interactive" ]; then
 
-configure_install $cc_upgrade
+configure_install
 [ $? -ne 0 ] && echo "Error configuring install parameters" && exit 1
 install_conf --set
-. $INSTALL_CONF/../configure --define_start_env &> /dev/null
+. $"$INSTALL_CONF/../configure" --define_start_env &> /dev/null
+[ $? -ne 0 ] && echo "Error configuring install environment" && exit 1
 
 export MODULES_LIST="DATABASE PARSER EVENT_HANDLERS SEARCH_ENGINE ADMIN_INTERFACE"
 echo "Please wait while checking modules configuration..."
@@ -77,8 +72,8 @@ for cc_mod in $NEED_CONFIG_MODULES; do
 done
 cc_err_msg=""
 while true; do
-#    clear
-    echo "The forward list shows modules that need to be configured."
+    echo -e "\nThe following list shows modules that are configurable."
+    echo "Modules not shown in this list are not configurable at this stage."
     echo "Modules checked with X have a valid configuration."
     cc_index=1
     all_ok=true
@@ -124,8 +119,7 @@ while true; do
 done
 choice_yn "\nCampsite configuration is completed. Do you want to review it?" Y
 if [ "$choice" = "Y" ]; then
-    clear
-    echo "Install configuration"
+    echo -e "\nInstall configuration"
     install_conf
     echo -e "\nTo continue press ENTER"
     read
@@ -140,4 +134,94 @@ fi
 
 fi # interactive
 
+}
+
+
+read_parameter()
+{
+param=$1
+def_val=$2
+explanation=$3
+
+[ "$3" != "" ] && echo -e "- $1: $3"
+echo -e -n "\tEnter $1 value"
+[ "$2" != "" ] && echo -n " [$2]"
+echo -n ": "
+read -r val
+if [ "$val" = "" ]; then
+    val=$2
+fi
+export $1="$val"
+return 0
+}
+
+read_instance_parameters()
+{
+read_parameter database_server_address 127.0.0.1 "The IP address of the MySQL server - usualy localhost"
+read_parameter database_user root "The user is needed to connect to the database server"
+read_parameter database_password "" "The password is needed to connect to the database server"
+read_parameter smtp_server_address 127.0.0.1 "The IP address of the email server - usualy localhost"
+}
+
+read_advanced_instance_parameters()
+{
+read_parameter database_server_port 0 "This is the database server listening port - 0 means\nuse default"
+read_parameter template_engine_port 0 "This is the template engine server listening port -\n0 means use default"
+read_parameter template_engine_max_threads 0 "This sets the maximum number of threads for the\ntemplate engine - 0 means use default"
+read_parameter smtp_server_port 25 "This is the email server listening port - default 25"
+read_parameter apache_user $"$APACHE_USER" "The owner of instance files; the template engine will run\nwith this user id - default apache user should work ok"
+read_parameter apache_group $"$APACHE_GROUP" "The group owner of instance files; the template engine will\nrun with this group id - default apache group should work ok"
+}
+
+args=(--db_server_address --db_user --db_password --smtp_server_address --db_server_port \
+      --parser_port --parser_max_threads --smtp_server_port --apache_user --apache_group)
+params=(database_server_address database_user database_password smtp_server_address \
+        database_server_port template_engine_port template_engine_max_threads smtp_server_port \
+	apache_user apache_group)
+
+install_default_instance()
+{
+echo "The base package was installed. In order for Campsite to work you must install"
+echo "at least one instance."
+
+if [ "$1" != "Y" ]; then
+    choice_yn "Do you want to install the default Campsite instance?" "Y"
+    if [ $? -ne 0 ]; then
+	# The choice was no
+        return 0
+    fi
+fi
+choice_yn "Do you want to change the instance base parameters?" "N"
+if [ $? -eq 0 ]; then
+    echo ""
+    read_instance_parameters
+    echo ""
+fi
+apache_user=
+apache_group=
+choice_yn "Do you want to change the instance advanced parameters?" "N"
+if [ $? -eq 0 ]; then
+    echo ""
+    read_advanced_instance_parameters
+    echo ""
+fi
+cli_args=""
+index=0
+while [ $index -le 9 ]; do
+    param_name=${params[$index]}
+    arg_name=${args[$index]}
+    param_value=${!param_name}
+    if [ "$param_value" != "" ]; then
+	cli_args="$cli_args  $arg_name $param_value"
+    fi
+    index=`expr $index + 1`
+done
+echo -e "\nRunning $BIN_DIR/create_instance"
+if [ "$cli_args" != "" ]; then
+    echo -e "with the following arguments: $cli_args\n"
+else
+    echo -e "with no arguments (use default values)\n"
+fi
+$BIN_DIR/create_instance $cli_args && export DEF_INST_INSTALLED=Y && return 0
+return 1
 }
diff --git a/campsite/install b/campsite/install
--- a/campsite/install
+++ b/campsite/install
@@ -4,7 +4,7 @@ do_configure()
 {
     rm -f install_log
     echo -e "\nSTEP 1"
-    echo -n "Configuring campsite (this may take a while, please wait)..."
+    echo -n "Configuring Campsite (this may take a while, please wait)..."
     echo -e "###############################################\n\tConfiguring campsite\n" >> install_log
     ./configure $* >> install_log 2>&1
     err_code=$?
@@ -36,42 +36,62 @@ compile_sources()
 install_campsite()
 {
     echo -e "\nSTEP 3"
-    echo -n "Installing CAMPSITE..."
+    echo -e "Installing Campsite...\n"
     echo -e "\n\n###############################################\n\tInstalling campsite\n" >> install_log
     $MAKE install >> install_log 2>&1
-    $MAKE default_instance >> install_log 2>&1
-    err_code=$?
-    if [ $err_code -ne 0 ]; then
-	rm -f ./campsite_upgrade
+    if [ $? -ne 0 ]; then
 	echo "ERROR."
 	echo "Read install_log for more information on installation error."
 	echo "Please report bug to http://bugs.campware.org"
 	exit 1
     fi
-    echo -e "done\n\nCAMPSITE was installed successfully."
-    echo "For a complete installation log read install_log file."
-    echo -n -e "\nStarting campsite_server daemon..."
-    "$BIN_DIR/campsitectl" stop &> /dev/null
-    "$BIN_DIR/campsitectl" start
-    err_code=$?
-    if [ $err_code -ne 0 ]; then
-	echo "ERROR"
+    def_inst_error=0
+    do_install=
+    while true; do
+	install_default_instance $do_install
+	if [ $? -ne 0 ]; then
+	    echo "There were errors creating the default instance"
+	    choice_yn "Do you want to try again?" "Y"
+	    if [ $? -ne 0 ]; then
+		def_inst_error=1
+		break
+	    else
+		do_install=Y
+	    fi
+	else
+	    break
+	fi
+    done
+    if [ $def_inst_error -ne 0 ]; then
+	echo -e "\nError creating the default Campsite instance. This usually happens when"
+	echo "MySQL configuration is different from the default one or you did not"
+	echo "install an email server. Run:"
+	echo "$BIN_DIR/create_instance --help"
+	echo "to find out how to set Campsite instance parameters."
+	echo -e "\nIMPORTANT!!!"
     else
-	echo "done"
+	echo -e "\nCampsite was installed successfully."
+	echo "For a complete installation log read install_log file."
+	echo -n -e "\nStarting campsite_server daemon..."
+	"$BIN_DIR/campsitectl" stop &> /dev/null
+	"$BIN_DIR/campsitectl" start
+	if [ $? -ne 0 ]; then
+	    echo "ERROR"
+	else
+	    echo "done"
+	fi
+	echo -e "\nIMPORTANT!!!\n"
     fi
-    echo -e "\nIMPORTANT!!!"
-    echo "Please configure apache server before using CAMPSITE application; make sure"
+    echo "Please configure apache server before using Campsite application; make sure"
     echo -e "the crond daemon is running; read INSTALL file and follow the instructions.\n"
-    echo "To enter the CAMPSITE administration site start a browser and type in the"
-    echo "following URL: http://localhost/admin/."
-    if [ -f ./campsite_upgrade ]; then
-	echo -e "\nYour older database was preserved. You should log in to the CAMPSITE"
-	echo "administration site using the old user and password."
-    else
-        echo -e "Fill in \"admin\" and \"admn00\" user and password respectivelly to log in."
+    if [ "$DEF_INST_INSTALLED" = "Y" ]; then
+	echo "To enter the Campsite administration site start a browser and type in the"
+	echo "following URL: http://[\$SERVER_NAME]/admin/."
+	echo -e "Fill in \"admin\" and \"admn00\" user and password respectivelly to log in."
 	echo "You should change the password as soon as possible."
+    else
+	echo "Run create_instance script in order to complete Campsite install."
     fi
-    rm -f ./campsite_upgrade
 }
 
 
@@ -81,12 +101,10 @@ if [ ! -x ./configure ]; then
     exit 1
 fi
 go_to_install=false
-upgrade=""
 do_interactive="--interactive"
 while [ "$1" != "" ]; do
     case $1 in
     --go_to_install) go_to_install=true ;;
-    --upgrade) upgrade=--upgrade ;;
     --not_interactive) do_interactive=""
     esac
     shift 1
@@ -97,13 +115,14 @@ if [ "`uname | grep BSD`" != "" ]; then
 else
 	export BSD=0
 fi;
+echo -n "Preparing install scripts..."
 . ./configure --define_start_env
 [ $? -ne 0 ] && exit 1
+echo "done"
 if [ "$go_to_install" = "true" ] && [ $my_id -eq 0 ]; then
     install_campsite
     exit 0
 fi
-#clear
 . ${INSTALL_CONF}/install_functions
 if [ $? -ne 0 ]; then
     echo "Error reading install files."
@@ -116,16 +135,16 @@ if [ "$1" = "--version" ]; then
     exit 0
 fi
 echo -e "\nInstalling CAMPSITE $CAMPSITE_VERSION $RELEASE_NAME"
-configure_campsite $upgrade $do_interactive
-do_configure $upgrade --apache_conf_path "$apache_conf_path" --apache_bin_path "$apache_bin_path"
+configure_campsite $do_interactive
+do_configure --apache_conf_path "$apache_conf_path" --apache_bin_path "$apache_bin_path"
 compile_sources
-make test_install &> /dev/null
+$MAKE test_install &> /dev/null
 if [ $? -ne 0 ] && [ $my_id -ne 0 ] && ! $USER_INSTALL; then
-    echo -e "\nThe root password is needed in order to install campsite. Please supply password."
+    echo -e "\nThe root password is needed in order to install campsite."
     while true; do
 	echo -n "Root password: "
 	archive_path=`pwd`
-	su - --command="echo \"\"; cd $archive_path; ./install --go_to_install" 2> /dev/null
+	su - $ROOT_USER -c "echo \"\"; cd $archive_path; ./install --go_to_install" 2> /dev/null
 	err_code=$?
 	if [ $err_code -ne 0 ]; then
 	    echo -n -e "\nThe password was not correct. Try again (Y/N) ? [Y]: "
