*** empty log message ***

diff --git a/campsite/implementation/parser/parser/install_parser b/campsite/implementation/parser/parser/install_parser
--- a/campsite/implementation/parser/parser/install_parser
+++ b/campsite/implementation/parser/parser/install_parser
@@ -30,16 +30,21 @@ echo "Stop old version server (if installed)"
 test -f $BIN_DIR/$CAMPSITECTL && $BIN_DIR/$CAMPSITECTL stop
 rm -f $BIN_DIR/$CAMPSITE_SERVER
 cp -f $CAMPSITE_SERVER $BIN_DIR
+chown ${ROOT_USER}.${HTTP_GROUP} ${BIN_DIR}/$CAMPSITE_SERVER
 chmod 750 $BIN_DIR/$CAMPSITE_SERVER
+chmod +s $BIN_DIR/$CAMPSITE_SERVER
 cp -f $CAMPSITECTL $BIN_DIR
+chown ${ROOT_USER}.${HTTP_GROUP} ${BIN_DIR}/$CAMPSITECTL
 chmod 755 $BIN_DIR/$CAMPSITECTL
 if [ -d $RC_INIT ]; then
 	cp -f $CAMPSITEINIT $RC_INIT
+	chown ${ROOT_USER}.${HTTP_GROUP} ${RC_INIT}/$CAMPSITEINIT
+	[ $? -ne 0 ] && echo "ERROR installing start/stop script" && exit 1
 	chmod 755 $RC_INIT$CAMPSITEINIT
-	test -f $RC_INIT$CAMPSITEINIT && ln -s $RC_INIT$CAMPSITEINIT /etc/rc.d/rc3.d/S95$CAMPSITEINIT
-	test -f $RC_INIT$CAMPSITEINIT && ln -s $RC_INIT$CAMPSITEINIT /etc/rc.d/rc5.d/S95$CAMPSITEINIT
-	test -f $RC_INIT$CAMPSITEINIT && ln -s $RC_INIT$CAMPSITEINIT /etc/rc.d/rc0.d/K50$CAMPSITEINIT
-	test -f $RC_INIT$CAMPSITEINIT && ln -s $RC_INIT$CAMPSITEINIT /etc/rc.d/rc6.d/K50$CAMPSITEINIT
+	ln -s $RC_INIT$CAMPSITEINIT /etc/rc.d/rc3.d/S95$CAMPSITEINIT
+	ln -s $RC_INIT$CAMPSITEINIT /etc/rc.d/rc5.d/S95$CAMPSITEINIT
+	ln -s $RC_INIT$CAMPSITEINIT /etc/rc.d/rc0.d/K50$CAMPSITEINIT
+	ln -s $RC_INIT$CAMPSITEINIT /etc/rc.d/rc6.d/K50$CAMPSITEINIT
 elif [ -d /etc/rc.d ]; then
 	if [ ! -f /etc/rc.d/rc.local ]; then
 		echo -e "#!/bin/sh\n" > /etc/rc.d/rc.local
@@ -47,5 +52,10 @@ elif [ -d /etc/rc.d ]; then
 	grep -w $CAMPSITECTL /etc/rc.d/rc.local > /dev/null
 	if [ "$?" != "0" ]; then
 		echo "$BIN_DIR/$CAMPSITECTL start" >> /etc/rc.d/rc.local
+		[ $? -ne 0 ] && echo "ERROR installing start/stop script" && exit 1
 	fi
 fi
+mkdir -p $CONF_DIR
+echo -e "THREADS $PARSER_THREADS\nPORT $PARSER_PORT\nALLOWED_HOSTS $PARSER_ALLOWED_HOSTS\nUSER $PARSER_USER\nGROUP $PARSER_GROUP\n" > ${CONF_DIR}/parser.conf
+[ $? -ne 0 ] && echo "Error writing parser configuration file" && exit 1
+exit 0
