*** empty log message ***

diff --git a/campsite/implementation/management/src/configure b/campsite/implementation/management/src/configure
--- a/campsite/implementation/management/src/configure
+++ b/campsite/implementation/management/src/configure
@@ -35,3 +35,8 @@ EOF
 [ $? -ne 0 ] && echo "ERROR" && exit 1
 echo OK
 chmod o-rwx sql_connect.h
+
+echo -n -e "\t\tWriting dir_conf.h header..."
+m4 ../macros.m4 dir_conf.m4 > dir_conf.h
+[ $? -ne 0 ] && echo "ERROR" && exit 1
+echo OK
